#!/bin/bash

# exit on error
set -e

# set variables
container_ip_address="$(hostname --ip-address)"

# update user id of webserver user to the owner of this init script
webserver_uid="$(stat -c "%u" "$0")"
webserver_orig_uid="$(id -u webserver)"
if [ "$webserver_uid" -lt "500" ] || [ "$webserver_uid" -gt "1999" ]
then
    echo "The tugger-stack 'init' script's owner user id will be used as user id for the webserver user in your"
    echo "container. Please use the user id of your own local user to avoid permission issues. The user id has to be"
    echo "between 500 and 1999."
    exit 1
fi
if [ "$webserver_uid" != "$webserver_orig_uid" ]
then
    usermod -u $webserver_uid webserver
    if test -e /var/lock/apache2; then
        chown -R $webserver_uid /var/lock/apache2
    fi
    if test -e /var/cache/apache2; then
        chown -R $webserver_uid /var/cache/apache2
    fi
    if test -e /var/lib/php/sessions; then
        chown -R $webserver_uid /var/lib/php/sessions/*
    fi
fi

# stop services (not required during normal startup, but during provisioning)
echo "Stopping services..."
service ssh stop
service mysql-default stop
service apache2 stop
service elasticsearch stop
service redis-server stop
echo "Services stopped."

# start services
echo "Starting services..."
# - ssh
if test -e /var/run/sshd.pid
then
    rm /var/run/sshd.pid
fi
service ssh start
# - mysql
if test -e /var/run/mysql-default/mysqld.pid
then
    rm /var/run/mysql-default/mysqld.pid
fi
if test -e /var/run/mysqld/mysqld.sock
then
    rm /var/run/mysqld/mysqld.sock
fi
if test -e /var/run/mysqld/mysqld.sock.lock
then
    rm /var/run/mysqld/mysqld.sock.lock
fi
service mysql-default start
# - apache2
if test -e /var/run/apache2/apache2.pid
then
    rm /var/run/apache2/apache2.pid
fi
service apache2 start
# - elasticsearch
service elasticsearch start
# - redis
if test -e /var/run/redis/redis-server.pid
then
    rm /var/run/redis/redis-server.pid
fi
service redis-server start
echo "Services started."
echo "The default password of the webserver user and the database root user is: qweqwe"
